### ISSUE TITLE
Bundling support for email notifications and email settings

### ISSUE THREAD

**Issue by gondzo** [topcoder-platform/tc-notifications#40]
Add support for bundling emails end email settings. 

Notifications settings endpoints should be updated to save preferences for emails (same as what we are doing for web preferences now). Additionally, there should be a bundle setting for emails with options: no bundling, 10 minutes, 1 hour, 24 hours, weekly (these should be configurable levels).
When a notification is created, email should not be sent right away, but we should first check email settings and send it immediately if email bundling is off. Otherwise, the email for that notification will be sent later.

All bundle intervals should be handled via scheduled jobs. At each interval check for new notifications that require emails to be sent and send bundle email containing all notifications created since last sending the email.

@vikasrohit should we create a new email event in kafka and new template in sendgrid for this one?

**Comment by vikasrohit** [comment]
> Otherwise, the email for that notification will be sent later.

**Comment by vikasrohit** [comment]
`notifications.action.email.connect.project.bundled` is created in kafka.

**Comment by maxceem** [comment]
1. Should we be able to config bundling time per notifications type? or for all notifications types there is same bundling time?

2. Should we bundle notifications of all types to one email? Or we bundle separately notifications of different types?

3. Do you know any good module for scheduling jobs for node?
    As I understand we need our job to be persistent between service relaunches, so the scheduler has to be able to store jobs somewhere. For example, [agenda](https://github.com/agenda/agenda) stores in the MongoDB, though I would prefer not to introduce another DB for this service as we already use PostgreSQL.
   I'll research now, but if have something to advise it would be great.

**Comment by maxceem** [comment]
4. For example we bundle notifications by 24 hours. Should we count 24h from some fixed time, like all notifications which comes from 00.00 till 23:59. Or from the first notification time occure, so if we got some first notification at 3:47am, than we wait 24h since than, and after we send the bundle at 3:47am the next day.

**Comment by vikasrohit** [comment]
Great questions @maxceem.!

1 and 2 we should group config and bundle per notification server e.g. in
this case connectNotificationServer.

3. We are thinking of using node cron module for scheduling and simple
storage of all job runs in existing posters db. Or you can try quartz with
posters. Still I would prefer simple node cron unless there is a specific
reason.

4.I would come back for this. @gondzo what do you think?

On May 8, 2018 4:33 PM, "maxceem" <notifications@github.com> wrote:


   1. For example we bundle notifications by 24 hours. Should we count 24h
   from some fixed time, like all notifications which comes from 00.00 till
   23:59. Or from the first notification time occure, so if we got some first
   notification at 3:47am, than we wait 24h since than, and after we send the
   bundle at 3:47am the next day.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/topcoder-platform/tc-notifications/issues/40#issuecomment-387366391>,
or mute the thread

**Comment by maxceem** [comment]
5. Is it possible to obtain long last admin token for dev environment to configure `TC_ADMIN_TOKEN`? 
    The one that provided in the [docs](https://github.com/topcoder-platform/tc-notifications) is expired. And if I create by myself they expire in few minutes and I have to create again.

**Comment by maxceem** [comment]
6. As I understand from 1 and 2 in one bundled notification could be notifications about different posts and projects. How in this case should we build `replyTo` email address? So far it's created for one particular topic.
    ```js
     const replyTo = `${config.REPLY_EMAIL_PREFIX}+${topicId}/${token}@${config.REPLY_EMAIL_DOMAIN}`;
     ```

**Comment by maxceem** [comment]
7. SImilar to previous one. What do you think we should put to email `from` name? Currently we put the handle of the user who triggered the event. For example user who added some post. In bundled email could be posts from various users.

**Comment by vikasrohit** [comment]
> How in this case should we build replyTo email address?

We don't want users replying bundled emails. Please use `noreply AT topcoder DOT com`.

> What do you think we should put to email from name?

We don't need the name here. Just use the same `noreply AT topcoder DOT com`

**Comment by maxceem** [comment]
8. Do you have any preferences what should be a bundled event payload? So far I'm thinking to have values like `recipients`, `replyTo`, `cc`, `from`, `categories` only one per events as it is. And send `data` as arrays of `data` of all bundled events:

   ![event-payload](https://user-images.githubusercontent.com/146016/39804090-aea82244-53a5-11e8-9dff-82114641933d.png)

   Do you have any requirements here?

**Comment by gondzo** [comment]
4. I think just having fixed intervals should be good enough, without taking into account when the first notification was created. For daily and weekly intervals, it would be good to configure time of day that we send the emails (so we don't end up sending all emails at midnight)

**Comment by gondzo** [comment]
8. I'm not really sure here - we use sendgrid templating to populate the email using that data field, but looks like they don't yet support loops in templates https://github.com/sendgrid/sendgrid-nodejs/issues/221

As I see it, we can either 
- create the final HTML in notifications service (containing the entire list of emails),  or
- add loop support to our email service (manually unroll sendgrid templates), for example as done here https://github.com/sendgrid/sendgrid-nodejs/issues/221#issuecomment-363739901

@vikasrohit thoughts?

**Comment by vikasrohit** [comment]
@maxceem Nice approach.

I have few queries though:

1. How the bundle id would be generated? And who would generate it?

2. instead of removing the sent events, can we just update the status 'completed'?

3. Event coming in the system (current version of tc-notifications) won't be something like `notifications.action.email.connect.project.bundled` but would be like `notifications.connect.project.topic.created` or `notifications.connect.project.post.created` and each of such event might require sending emails to multiple users. We can dispatch `notifications.action.email.connect.project.bundled` with custom data from tc-notifications after deducing that certain users from the list of target users requires bundled emails instead of instant emails. Now it is upto us, what data we send in that event. And we would consume this event in our scheduler. I guess now you would be creating the bundle id and dumping the payload in the table you mentioned (with status being pending), right?
If yes, then I guess we are okay because each such event would always have single user's data for single original event (`notifications.connect.project.topic.created` or `notifications.connect.project.post.created`). Now we can track which event for a particular user is pending or completed or errored out.

4. Instead of period, can we put frequency with values like hourly, daily or weekly or monthly? Does this affect configurability of possible frequencies?

**Comment by vikasrohit** [comment]
> anything else? these column I can place for visiblity, they are not requried for any functions, so we can output any useful info

We can store the target entity id with column name like `referenceId` and `reference` e.g. for a topic created event we can have `reference=topic` and `referenceId=<id of the topic>`. That would also help us in debugging production issues quickly. I am not sure if we can populate these two fields always for all events but I think we can. Let me know if you or @gondzo have any case where these fields can not be populated.

>  just have to configure values in the tc-ontifications and community-app

You mean connect-app, right?

Overall it looks good to me @maxceem. Nice work. I am assuming you are making the changes in `tc-notifications` to store the records in this table along with the scheduler changes.

**Comment by maxceem** [comment]
@vikasrohit I don't see any problem with adding `reference` and `referenceId`, I'll keep them optional, though.
So the final scheme would be:

![image](https://user-images.githubusercontent.com/146016/39912963-e593f574-5532-11e8-9d9f-810f4d5cc167.png)

>You mean connect-app, right?

yes, `connect-app`
