### ISSUE TITLE
Unsubscribe link

### ISSUE THREAD

**Issue by gondzo** [topcoder-platform/tc-notifications#63]
In the current emails we have two links to unsubscribe - one at sendgrid and one at connect 
![image](https://user-images.githubusercontent.com/3051646/45292086-67207380-b4f4-11e8-8a13-0440f0622f2c.png)

@vikasrohit can we remove the sendgrid link? I'm not sure where in sendgrid is it configured

**Comment by vikasrohit** [comment]
@gondzo Its difficult to remove the sendgrid one because that is present in the compulsory unsubscribe section of emails. If we remove that, we have to add the unsubscribe option to each and every other template where we require unsubscribe option.

I think we are okay with these two options because `Notification Settings` lets the user choose the specific event they want to op in or opt out while the default sendgrid option lets them disable any communication from topcoder.

**Comment by vikasrohit** [comment]
@vic-topcoder @acshields your thoughts?

**Comment by gondzo** [comment]
The main issue I have with that unsubscribe link is that there is no way to undo that if I click it accidentally. Maybe we could also add sendgrid subscription preferences link too https://sendgrid.com/docs/ui/sending-email/recipient-subscription-preferences/ (I'm not sure if this will let the user subscribe again after he unsubscribed, but it sounds like it)

**Comment by vikasrohit** [comment]
I guess that is product call. IMO, the global unsubscribe link is more or less for legal compliance while our `Notification Settings` allows users to unsubscribe/subscribe from specific group of emails. Now, if we use Sendgrid's email preferences, that might cause confusion to the users and we might have to provide an integration between Sendgrid and our email preferences. So, I would rather not like to go with that at present.

fyi @vic-topcoder @acshields

**Comment by acshields** [comment]
@vikasrohit - agreed with your assessment.

**Comment by vikasrohit** [comment]
Thanks @acshields for the confirmation. Closing the issue @gondzo.
